Q1) Write a Python Program to Add Two Matrices?


In [1]:
import numpy as np

a = np.matrix([[-1,1]])
b = np.matrix([[1,-1]])
print(f'{a} + {b} = {a+b}')

[[-1  1]] + [[ 1 -1]] = [[0 0]]


Q2) Write a Python Program to Multiply Two Matrices?

In [2]:
a = np.matrix([[-1,1]])
b = np.matrix([[1], [-1]])
print(f'{a} + {b} = {np.matmul(a,b)}')

[[-1  1]] + [[ 1]
 [-1]] = [[-2]]


Q3) Write a Python Program to Transpose a Matrix?

In [3]:
a = np.matrix([[-1,1]])
print(f'{a} transpos = {a.T}')

[[-1  1]] transpos = [[-1]
 [ 1]]


Q4) Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
array = ['banana', 'apple', 'zebra', 'orange']
sorted(array)

['apple', 'banana', 'orange', 'zebra']

Q5) Write a Python Program to Remove Punctuation From a String?

In [5]:
def remove_punc(strr):
    punc = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
    for i in strr:
        if i in punc:
            strr = strr.replace(i,"")
    return strr 

strr = 'asdhlsjfh3278529\ad?<'
print(f'removing punctuation from "{strr}" = "{remove_punc(strr)}"')

removing punctuation from "asdhlsjfh3278529d?<" = "asdhlsjfh3278529d"
